# Generated by Django 2.2.7 on 2020-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_expensepaidamount_total_paid_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepaidamount',
            name='pub',
            field=models.FloatField(null=True),
        ),
    ]
