# Generated by Django 2.2.7 on 2020-05-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_expensepaidamount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepaidamount',
            name='purchase',
            field=models.FloatField(default=0, null=True),
        ),
    ]
