# Generated by Django 2.2.7 on 2020-05-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_expensepaidamount_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubbillamount',
            name='date',
        ),
        migrations.AddField(
            model_name='pubbillamount',
            name='cur_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pubbillamount',
            name='cur_read',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pubbillamount',
            name='pre_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pubbillamount',
            name='prev_read',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pubbillamount',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pubbillamount',
            name='refuse_amt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pubbillamount',
            name='total_amt',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pubbillamount',
            name='total_units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pubbillamount',
            name='water_amt',
            field=models.FloatField(default=0),
        ),
    ]
